name: fsd_lint
description: Lint rules for Feature Sliced Design architecture
repository: https://github.com/dennis-emstone/fsd_lint
version: 0.1.0
publish_to: "none"

environment:
  sdk: ^3.10.1

dependencies:
  analyzer: ^8.4.0
  analyzer_plugin: ^0.13.10
  custom_lint_builder: ^0.8.1

dev_dependencies:
  custom_lint: ^0.8.1
